"""Add theme preference to User model

Revision ID: 0f1fec7d8e75
Revises: 7d8040d92e69
Create Date: 2025-04-26 22:08:15.823742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1fec7d8e75'
down_revision = '7d8040d92e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic, adjusted for SQLite ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10),
                                      nullable=False,
                                      server_default=sa.text("'light'"))) 

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic, adjusted for SQLite ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme')
    # ### end Alembic commands ###
