"""Add start_date and end_date to Book model

Revision ID: 47edc9ca7552
Revises: 6c74676c0213
Create Date: 2025-04-24 21:27:18.169900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47edc9ca7552'
down_revision = '6c74676c0213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
