"""Add BookShare model and relationships for book sharing

Revision ID: 51d9c819a7b9
Revises: 75955be8f2aa
Create Date: 2025-04-29 23:11:38.110447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d9c819a7b9'
down_revision = '75955be8f2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'shared_with_user_id', name='uq_book_share')
    )
    with op.batch_alter_table('book_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_shares_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_shares_shared_with_user_id'), ['shared_with_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_shares_shared_with_user_id'))
        batch_op.drop_index(batch_op.f('ix_book_shares_book_id'))

    op.drop_table('book_shares')
    # ### end Alembic commands ###
