"""Integrate Flask-Login and update User model

Revision ID: 7d8040d92e69
Revises: 47edc9ca7552
Create Date: 2025-04-25 14:57:27.316027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8040d92e69'
down_revision = '47edc9ca7552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
